"""added new table for status creation

Revision ID: 66de78dd7fd2
Revises: 7d7655d5b10c
Create Date: 2021-05-19 11:33:14.386884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66de78dd7fd2'
down_revision = '7d7655d5b10c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsstatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newsstatus')
    # ### end Alembic commands ###
