"""nullable calls

Revision ID: c6f8b3eb0459
Revises: 3c9c2373d673
Create Date: 2021-05-19 13:40:02.817626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6f8b3eb0459'
down_revision = '3c9c2373d673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsstatus', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('unionpos', schema=None) as batch_op:
        batch_op.alter_column('positionName',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unionpos', schema=None) as batch_op:
        batch_op.alter_column('positionName',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('newsstatus', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
